/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsDemoRouteImport } from './routes/analytics-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenMapRouteImport } from './routes/citizen.map'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as AdminIssuesIndexRouteImport } from './routes/admin.issues.index'
import { Route as AdminIssuesIdRouteImport } from './routes/admin.issues.$id'
import { Route as CitizenIssuesIndexRouteImport } from './routes/citizen.issues.index'
import { Route as CitizenIssuesIdRouteImport } from './routes/citizen.issues.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDemoRoute = AnalyticsDemoRouteImport.update({
  id: '/analytics-demo',
  path: '/analytics-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen/dashboard',
  path: '/citizen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenMapRoute = CitizenMapRouteImport.update({
  id: '/citizen/map',
  path: '/citizen/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/citizen/profile',
  path: '/citizen/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesIndexRoute = AdminIssuesIndexRouteImport.update({
  id: '/admin/issues/',
  path: '/admin/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesIdRoute = AdminIssuesIdRouteImport.update({
  id: '/admin/issues/$id',
  path: '/admin/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIssuesIndexRoute = CitizenIssuesIndexRouteImport.update({
  id: '/citizen/issues/',
  path: '/citizen/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIssuesIdRoute = CitizenIssuesIdRouteImport.update({
  id: '/citizen/issues/$id',
  path: '/citizen/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics-demo': typeof AnalyticsDemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/citizen/issues/$id': typeof CitizenIssuesIdRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/citizen/issues/': typeof CitizenIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics-demo': typeof AnalyticsDemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/citizen/issues/$id': typeof CitizenIssuesIdRoute
  '/admin/issues': typeof AdminIssuesIndexRoute
  '/citizen/issues': typeof CitizenIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics-demo': typeof AnalyticsDemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/citizen/issues/$id': typeof CitizenIssuesIdRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/citizen/issues/': typeof CitizenIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics-demo'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/map'
    | '/admin/users'
    | '/citizen/dashboard'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/admin/issues/$id'
    | '/citizen/issues/$id'
    | '/admin/issues/'
    | '/citizen/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics-demo'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/map'
    | '/admin/users'
    | '/citizen/dashboard'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/admin/issues/$id'
    | '/citizen/issues/$id'
    | '/admin/issues'
    | '/citizen/issues'
  id:
    | '__root__'
    | '/'
    | '/analytics-demo'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/map'
    | '/admin/users'
    | '/citizen/dashboard'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/admin/issues/$id'
    | '/citizen/issues/$id'
    | '/admin/issues/'
    | '/citizen/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsDemoRoute: typeof AnalyticsDemoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenMapRoute: typeof CitizenMapRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReportRoute: typeof CitizenReportRoute
  AdminIssuesIdRoute: typeof AdminIssuesIdRoute
  CitizenIssuesIdRoute: typeof CitizenIssuesIdRoute
  AdminIssuesIndexRoute: typeof AdminIssuesIndexRoute
  CitizenIssuesIndexRoute: typeof CitizenIssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics-demo': {
      id: '/analytics-demo'
      path: '/analytics-demo'
      fullPath: '/analytics-demo'
      preLoaderRoute: typeof AnalyticsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/map': {
      id: '/citizen/map'
      path: '/citizen/map'
      fullPath: '/citizen/map'
      preLoaderRoute: typeof CitizenMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/issues/': {
      id: '/admin/issues/'
      path: '/admin/issues'
      fullPath: '/admin/issues/'
      preLoaderRoute: typeof AdminIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/issues/$id': {
      id: '/admin/issues/$id'
      path: '/admin/issues/$id'
      fullPath: '/admin/issues/$id'
      preLoaderRoute: typeof AdminIssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/issues/': {
      id: '/citizen/issues/'
      path: '/citizen/issues'
      fullPath: '/citizen/issues/'
      preLoaderRoute: typeof CitizenIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/issues/$id': {
      id: '/citizen/issues/$id'
      path: '/citizen/issues/$id'
      fullPath: '/citizen/issues/$id'
      preLoaderRoute: typeof CitizenIssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsDemoRoute: AnalyticsDemoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminUsersRoute: AdminUsersRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenMapRoute: CitizenMapRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReportRoute: CitizenReportRoute,
  AdminIssuesIdRoute: AdminIssuesIdRoute,
  CitizenIssuesIdRoute: CitizenIssuesIdRoute,
  AdminIssuesIndexRoute: AdminIssuesIndexRoute,
  CitizenIssuesIndexRoute: CitizenIssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
